
def get_flashcards():
    flashcards = [
        {"question": "Hello", "answer": "Namaste", "difficulty": "Easy"},
        {"question": "How are you?", "answer": "Aap kaise ho?", "difficulty": "Easy"},
        {"question": "Thank you", "answer": "Dhanyawad", "difficulty": "Easy"},
        {"question": "Yes", "answer": "Haan", "difficulty": "Easy"},
        {"question": "No", "answer": "Nahi", "difficulty": "Easy"},
        {"question": "Goodbye", "answer": "Alvida", "difficulty": "Easy"},
        {"question": "Water", "answer": "Pani", "difficulty": "Easy"},
        {"question": "Food", "answer": "Khana", "difficulty": "Easy"},
        {"question": "How are you feeling?", "answer": "Aap kaisa mehsoos kar rahe hain?", "difficulty": "Medium"},
        {"question": "I'm doing well, thank you", "answer": "Main theek hoon, dhanyavad", "difficulty": "Medium"},
        {"question": "What are you doing today?", "answer": "Aap aaj kya kar rahe hain?", "difficulty": "Medium"},
        {"question": "I'm going to the market", "answer": "Main bazaar ja rahi hoon", "difficulty": "Medium"},
        {"question": "Where are you from?", "answer": "Aap kahan se hain?", "difficulty": "Medium"},
        {"question": "I'm from the United States", "answer": "Main United States se hoon", "difficulty": "Medium"},
        {"question": "What do you do for a living?", "answer": "Aap kya karte hain?", "difficulty": "Medium"},
        {"question": "I'm a teacher", "answer": "Main ek shikshak hoon", "difficulty": "Medium"},
        {"question": "Do you speak English?", "answer": "Kya aap Angrezi bolte hain?", "difficulty": "Medium"},
        {"question": "A little bit", "answer": "Thoda bahut", "difficulty": "Medium"},
        {"question": "What do you think of India?", "answer": "Aapko India ke baare mein kya lagta hai?", "difficulty": "Hard"},
        {"question": "It's a beautiful country with a rich history", "answer": "Yeh ek sundar desh hai jiska itihas bahut aamir hai", "difficulty": "Hard"},
        {"question": "What are your plans for the future?", "answer": "Aapke bhavishya ke liye kya yojana hai?", "difficulty": "Hard"},
        {"question": "I'm not sure yet", "answer": "Mujhe abhi tak pata nahi", "difficulty": "Hard"},
        {"question": "What is your biggest dream?", "answer": "Aapka sabse bada sapna kya hai?", "difficulty": "Hard"},
        {"question": "To travel the world", "answer": "Duniya ghoomna", "difficulty": "Hard"},
        {"question": "What is the meaning of life?", "answer": "Jeevan ka matlab kya hai?", "difficulty": "Hard"},
        {"question": "That's a difficult question to answer", "answer": "Yeh jawab dena mushkil hai", "difficulty": "Hard"},
        {"question": "What is your favorite thing about learning Hindi?", "answer": "Hindi seekhne ke baare mein aapka kya pasand hai?", "difficulty": "Hard"},
        {"question": "Can you help me?", "answer": "Kya aap meri madad kar sakte hain?", "difficulty": "Easy"},
        {"question": "What is your name?", "answer": "Aapka naam kya hai?", "difficulty": "Easy"},
        {"question": "I need a doctor", "answer": "Mujhe ek doctor ki zarurat hai", "difficulty": "Easy"},
        {"question": "I am lost", "answer": "Main kho gayi hoon", "difficulty": "Easy"},
        {"question": "I love you", "answer": "Main tumse pyar karti hoon", "difficulty": "Easy"},
        {"question": "I feel happy", "answer": "Mujhe khushi mehsoos ho rahi hai", "difficulty": "Medium"},
        {"question": "What is the time?", "answer": "Samay kya hua hai?", "difficulty": "Medium"},
        {"question": "Can you show me the way?", "answer": "Kya aap mujhe rasta dikha sakte hain?", "difficulty": "Medium"},
        {"question": "I would like to order food", "answer": "Mujhe khana order karna hai", "difficulty": "Medium"},
        {"question": "Where is the nearest ATM?", "answer": "Nikatam ATM kahan hai?", "difficulty": "Medium"},
        {"question": "How much does it cost?", "answer": "Iska kya daam hai?", "difficulty": "Hard"},
        {"question": "Can we have the bill, please?", "answer": "Kya hum bill le sakte hain, kripya?", "difficulty": "Hard"},
        {"question": "I need to change money", "answer": "Mujhe paise badalne hain", "difficulty": "Hard"},
        {"question": "Could you recommend a good restaurant?", "answer": "Kya aap ek achha restaurant suggest kar sakte hain?", "difficulty": "Hard"},
        {"question": "I am allergic to nuts", "answer": "Mujhe nuts se allergy hai", "difficulty": "Hard"},
        {"question": "Is there a hospital nearby?", "answer": "Kya yahan ke aas-paas ek hospital hai?", "difficulty": "Hard"},
        {"question": "I would like a map of the city", "answer": "Mujhe shahar ka naksha chahiye", "difficulty": "Hard"},
        {"question": "Excuse me", "answer": "Kshama kijiye", "difficulty": "Easy"},
        {"question": "Please speak slowly", "answer": "Kripya dheere bolie", "difficulty": "Easy"},
        {"question": "How do I get to the train station?", "answer": "Train station kaise jaun?", "difficulty": "Medium"},
        {"question": "I would like a coffee", "answer": "Mujhe ek coffee chahiye", "difficulty": "Medium"},
        {"question": "Can I have some water?", "answer": "Kya mujhe thoda paani mil sakta hai?", "difficulty": "Medium"},
        {"question": "I'm shopping for clothes", "answer": "Main kapde khareed rahi hoon", "difficulty": "Medium"},
        {"question": "What's the weather like today?", "answer": "Aaj mausam kaisa hai?", "difficulty": "Medium"},
        {"question": "I'm looking for a pharmacy", "answer": "Main ek pharmacy dhoondh rahi hoon", "difficulty": "Medium"},
        {"question": "Can you recommend a good book?", "answer": "Kya aap ek achhi kitab recommend kar sakte hain?", "difficulty": "Hard"},
        {"question": "I'd like to make a reservation", "answer": "Main ek reservation karna chahti hoon", "difficulty": "Hard"},
        {"question": "What are the must-visit places here?", "answer": "Yahaan ke must-visit sthaan kaun se hain?", "difficulty": "Hard"},
        {"question": "Can I try this on?", "answer": "Kya main ise pehan kar dekh sakti hoon?", "difficulty": "Hard"},
        {"question": "How far is the city center?", "answer": "City center kitni door hai?", "difficulty": "Hard"},
        {"question": "I'm here on vacation", "answer": "Main yahaan chhuttiyon par hoon", "difficulty": "Hard"},
        {"question": "Is there a vegetarian option?", "answer": "Kya yahaan koi shakahari vikalp hai?", "difficulty": "Hard"},
        {"question": "Could you take a picture of me?", "answer": "Kya aap meri ek tasveer le sakte hain?", "difficulty": "Hard"},
        {"question": "Is this spicy?", "answer": "Kya yeh teekha hai?", "difficulty": "Easy"},
        {"question": "I'm vegetarian", "answer": "Main shakahari hoon", "difficulty": "Easy"},
        {"question": "Where is the bathroom?", "answer": "Bathroom kahaan hai?", "difficulty": "Easy"},
        {"question": "How do I connect to the Wi-Fi?", "answer": "Wi-Fi se kaise jude?", "difficulty": "Medium"},
        {"question": "I would like to buy a SIM card", "answer": "Mujhe ek SIM card kharidna hai", "difficulty": "Medium"},
        {"question": "What time does the store open?", "answer": "Dukaan kis samay khulti hai?", "difficulty": "Medium"},
        {"question": "Can I get a discount?", "answer": "Kya mujhe chhoot mil sakti hai?", "difficulty": "Medium"},
        {"question": "I need to go to the airport", "answer": "Mujhe hawai adda jaana hai", "difficulty": "Medium"},
        {"question": "Do you have a menu in English?", "answer": "Kya aapke paas Angrezi mein menu hai?", "difficulty": "Medium"},
        {"question": "I'm here for business", "answer": "Main yahaan business ke liye hoon", "difficulty": "Hard"},
        {"question": "Can you suggest a good hotel?", "answer": "Kya aap ek achha hotel suggest kar sakte hain?", "difficulty": "Hard"},
        {"question": "I have a reservation under the name...", "answer": "Mera reservation ... naam ke under hai", "difficulty": "Hard"},
        {"question": "Where can I find a taxi?", "answer": "Mujhe taxi kahaan milegi?", "difficulty": "Hard"},
        {"question": "Can you help me with the luggage?", "answer": "Kya aap mujhe samaan ke saath madad kar sakte hain?", "difficulty": "Hard"},
        {"question": "I'd like to cancel my booking", "answer": "Main apni booking cancel karna chahti hoon", "difficulty": "Hard"},
        {"question": "What local dishes do you recommend?", "answer": "Aap kaun se local dishes recommend karte hain?", "difficulty": "Hard"},
        {"question": "Do you offer room service?", "answer": "Kya aap room service dete hain?", "difficulty": "Hard"},
        {"question": "How do I get to the city center from here?", "answer": "Yahaan se main sheher ke centre tak kaise pahunchu?", "difficulty": "Hard"},
        {"question": "I'd like to rent a car", "answer": "Main ek car kiraye par lena chahti hoon", "difficulty": "Hard"}
    ]

    return flashcards

if __name__ == '__main__':
    get_flashcards()